# Generated by Django 2.2.4 on 2021-06-04 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Birthday',
            field=models.DateField(default=datetime.date(2021, 6, 4)),
        ),
    ]
