# Generated by Django 2.2.4 on 2021-06-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_user_birthday'),
        ('users_app', '0003_auto_20210605_1037'),
    ]

    operations = [
    ]
