# Generated by Django 2.2.4 on 2021-06-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Birthday',
        ),
    ]
