# Generated by Django 2.2.4 on 2021-06-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_remove_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
