# Generated by Django 2.2.4 on 2021-06-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0005_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_category',
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_cat', to='books_app.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.RemoveField(
            model_name='book',
            name='to_exchange_with',
        ),
        migrations.AddField(
            model_name='book',
            name='to_exchange_with',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_category', to='books_app.Category'),
        ),
        migrations.RemoveField(
            model_name='selling_method',
            name='book',
        ),
        migrations.AddField(
            model_name='selling_method',
            name='book',
            field=models.ManyToManyField(related_name='method', to='books_app.Book'),
        ),
    ]
